[features]
seeds = false
skip-lint = false

[programs.localnet]
pool_odds = "PoLoddsXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[programs.devnet]
pool_odds = "PoLoddsXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[programs.mainnet]
pool_odds = "PoLoddsXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "PoLoddsXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
program = "target/deploy/pool_odds.so"

[test.validator]
url = "https://api.devnet.solana.com"
clone = [
    { address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" },
    { address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" },
]

bind_address = "0.0.0.0"
rpc_port = 8899
websocket_port = 8900
ledger = ".anchor/test-ledger"
startup_wait = 5000
shutdown_wait = 2000
limit_ledger_size = 10000
